version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20.3.0
    commands:
      - echo not installing anything else  
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - tsc
      - npm run build
      - npm run export      
      - npm prune --production
    post_build:
      commands:
      - echo Build completed on `date`
      - aws s3 sync out s3://cicd-codebuild-static-website/
artifacts:
  type: zip
  files:
    - package.json
    - package-lock.json
    - "build/**/*"
    - .ebextensions/**/*
